### PR TITLE
newer ProRWTS2

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Comment by peterferrie** [comment]
This version supercedes the previous PR, and is confirmed working on both floppy and HDD loading.

**Comment by martinhaye** [comment]
Things are getting farther along. The loader completed, and the first memory manager request is starting to run.

Peter, I've done integration work that I'd like you to check if you have time. I had to remap all the zero page locations to their old values, and also adjust many assemble-time flags to hopefully match the old version of ProRWTS. If you wouldn't mind reviewing what I've done so far, it's on my "rwts_2021" branch here: https://github.com/martinhaye/lawless-legends/commits/rwts_2021

By the way, I verified that the save file is getting fully populated and isn't sparse. At least, I think it's verified: it's reported by "CATALOG" as taking 19 blocks on disk which is correct given the size.

Anyway, I think the first calls are read, seek, read. Something's going wrong there, but I'm out of time today to trace it down. In case it's useful, I've placed a hard drive image here: https://www.dropbox.com/s/6p82x7q59ck9ady/rwts_2021.2mg?dl=0

**Comment by peterferrie** [comment]
> Things are getting farther along. The loader completed, and the first memory
> manager request is starting to run.
>
> Peter, I've done integration work that I'd like you to check if you have
> time. I had to remap all the zero page locations to their old values, and
> also adjust many assemble-time flags to hopefully match the old version of
> ProRWTS. If you wouldn't mind reviewing what I've done so far, it's on my
> "rwts_2021" branch here:
> https://github.com/martinhaye/lawless-legends/commits/rwts_2021

It looks okay.  I forgot that you moved zpage addresses.  I'll update
my local copy to match.

> By the way, I verified that the save file is getting fully populated and
> isn't sparse. At least, I think it's verified: it's reported by "CATALOG" as
> taking 19 blocks on disk which is correct given the size.

Yes, it's not sparse anymore.

> Anyway, I think the first calls are read, seek, read. Something's going
> wrong there, but I'm out of time today to trace it down. In case it's
> useful, I've placed a hard drive image here:
> https://www.dropbox.com/s/6p82x7q59ck9ady/rwts_2021.2mg?dl=0

I'm looking now.  I see the crash.  It might be a mismatched setting,
but I'll work it out.

**Comment by peterferrie** [comment]
Immediate fix, if you can spare the memory: set "fast_subindex=1".
It turns out that readseq can't work without it.
Then it reaches the second decomp request, at least.

**Comment by martinhaye** [comment]
Oh nice, fast_subindex worked! Thanks for that. It doesn't seem to be taking more memory; buffers still end at $DAFF just like they used to.

I'll pick up tomorrow morning with the next step.

**Comment by peterferrie** [comment]
Second decomp has an memory-read overrun.  It looks like garbage at
the end of the compressed region is being used, but the content in
memory matches what's on disk, so I think that the disk access is
good.

**Comment by martinhaye** [comment]
I added some instrumentation so I could tell what the memory manager is doing with rwts. The sequence of calls leading up to the crash is: rewind, seek, read. This makes me wonder if my rewind logic isn't right for the new rwts. 

Currently the rewind clears $18, $19, $1a, $1b. That corresponds to rwts 'entries', 'blkofflo', 'blkoffhi', and 'treeidx'. Does that sound right to you Peter?

**Comment by peterferrie** [comment]
> Currently the rewind clears $18, $19, $1a, $1b. That corresponds to rwts
> 'entries', 'blkofflo', 'blkoffhi', and 'treeidx'. Does that sound right to
> you Peter?

blkidx needs to be updated, too.
If the file is < 128kb+1 then treeidx won't be in use.
If you can tell me the file offset that you intend to be hitting
before the call then I can see exactly what needs to be set to achieve
that.

**Comment by martinhaye** [comment]
I tried clearing blkidx too, but it didn't change the behavior.

The sequence of events I see is:
1. open file "GAME.PART.1" and read 2 bytes
2. read $2D9 bytes to $4C00
3. reseek
4. seek $A2D0
5. read $6BE bytes to $143B

The bytes read by the last call are very different, hence the decompression failure.

**Comment by peterferrie** [comment]
Using ProRWTS with the fastsubindex=1, I get a good boot, so the issue
seems to be fixed in the rwts_2021.2mg image that you shared.
Are you still seeing issues?

**Comment by martinhaye** [comment]
I had incorrectly rebuilt the image after moving blkidx so it gets cleared on a rewind. With that fixed, I have a good boot in hard drive mode. Hurray!

On to floppy mode debugging...

**Comment by martinhaye** [comment]
Floppy mode is also successfully booting on Virtual II! There's a problem further in but I think it's related to disk mark saving, which I haven't looked at yet. I've got time today.

In the meantime: Peter, any idea why Virtual II is making a floppy recalibration sound during the first call by the loader to RWTS? Just curious. Code is up to date in my branch, and here's a fresh dsk if that's useful: https://www.dropbox.com/s/1fuu4hz07xmn08u/rwts1.dsk?dl=0

**Comment by peterferrie** [comment]
> Floppy mode is also successfully booting on Virtual II! There's a problem
> further in but I think it's related to disk mark saving, which I haven't
> looked at yet. I've got time today.

Okay, let me know if there are questions.

> In the meantime: Peter, any idea why Virtual II is making a floppy
> recalibration sound during the first call by the loader to RWTS? Just
> curious. Code is up to date in my branch, and here's a fresh dsk if that's
> useful: https://www.dropbox.com/s/1fuu4hz07xmn08u/rwts1.dsk?dl=0

After drive 2 is detected, the arm is forced to track 0 to get a known
starting point.
That will likely cause the sound in Virtual II.  I will try it to know for sure.

**Comment by martinhaye** [comment]
Symptom: hangs forever in Virtual II when looking for disk in drive 2 but it hasn't been inserted. This happens after new game is selected and a character has been created.

It appears that Virtual II returns changing data on Q6L if the drive is spinning, even if a disk isn't present. When that happens, readd5aa hangs forever.

I developed this patch to check for real-looking data in polling mode. See what you think: https://github.com/martinhaye/lawless-legends/commit/b260002b4dee3bb9c2dad93c50c2f827314ebbfa

**Comment by peterferrie** [comment]
> Symptom: hangs forever in Virtual II when looking for disk in drive 2 but it
> hasn't been inserted. This happens after new game is selected and a
> character has been created.

Yes, I've been meaning to add a read-with-timeout to address that.

> It appears that Virtual II returns changing data on Q6L if the drive is
> spinning, even if a disk isn't present. When that happens, readd5aa hangs
> forever.

Sigh.

> I developed this patch to check for real-looking data in polling mode. See
> what you think:
> https://github.com/martinhaye/lawless-legends/commit/b260002b4dee3bb9c2dad93c50c2f827314ebbfa

That's the right idea, but I think that readd5aa itself should do
that, to handle the case that the user takes out the disk at the wrong
time.

**Comment by peterferrie** [comment]
However, backing out of the call chain correctly might be a bit tricky.
I'll work on fixing it.

**Comment by martinhaye** [comment]
If there's a handy spot to stash a copy of the stack register, that would simplify backing out. Just thinking out loud.

**Comment by peterferrie** [comment]
> If there's a handy spot to stash a copy of the stack register, that would
> simplify backing out. Just thinking out loud.

I came to the same conclusion eventually.

**Comment by peterferrie** [comment]
PR is updated.  prepdrive takes care of detecting if there's a disk in
the drive.
Floppy still boots for me.
However, AppleWin seems to have a bug where if the disk is removed
from the drive after being detected, then D5AA96 can still be read,
leading to a hang like before.
I need to investigate that a bit more and then take it up with them.

**Comment by martinhaye** [comment]
Ok, the polling fix worked, but the first rdwrfile on drive 2 failed. I tried selectively undoing parts of your commit until I found it. See my fix here: https://github.com/martinhaye/lawless-legends/commit/766e544c716128287fce4a9072fb7762e25730df

If you want to reproduce the bug yourself, you'll need to get all the way to disk 2. Steps:
1. Hit "N" for new
2. Space 6 times to get through the intro text screens
3. Character name. I always use "Foo"
4. Any letter for gender
5. Esc to exit character attributes
6. Display shows "Fort Miller" with a 3D view.

Disks here:
https://www.dropbox.com/s/1fuu4hz07xmn08u/rwts1.dsk?dl=0
https://www.dropbox.com/s/cnhm31ib9ww4ts5/rwts2.dsk?dl=0

**Comment by martinhaye** [comment]
At this point I'm starting to find bugs in non-disk related code, so it's time to for me to merge this PR. Thanks very, very much Peter for all your hard work and quick responses on this!

**Comment by peterferrie** [comment]
> Ok, the polling fix worked, but the first rdwrfile on drive 2 failed. I
> tried selectively undoing parts of your commit until I found it. See my fix
> here:
> https://github.com/martinhaye/lawless-legends/commit/766e544c716128287fce4a9072fb7762e25730df

Ah, okay.  Selected drive should be maintained across rdwrpart calls.
Your fix is good.  I fixed an unrelated issue (status was not always
initialised explicitly) and made a new PR.

**Pull request merged**
